version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./exports:/app/exports
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
